version: '3.6'
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    networks:
      - walking_rabbit_api_network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ../db-data-final:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  api:
    depends_on:
      db:
        condition: service_healthy
    build: .
    restart: always
    tty: true
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
    environment:
      NODE_ENV: ${NODE_ENV}
      SERVER_PORT: ${SERVER_PORT}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    volumes:
      - ./:/var/www/api
      - /var/www/api/node_modules
      - /tmp/uploads2:/tmp/uploads
    networks:
      - walking_rabbit_api_network
networks:
  walking_rabbit_api_network:
volumes:
  db-volume:
