version: '3.6'
services:
  db:
    image: postgis/postgis:15-3.3-alpine
    networks:
      - walking_rabbit_api_network
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      PGDATA: /data/postgres
      PGPORT: ${DB_PORT}
    ports:
      - ${DB_PORT}:${DB_PORT}
    volumes:
      - ../db-data:/data/postgres
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: 'redis:alpine'
    command: redis-server --save 20 1 --loglevel warning
    ports:
      - '6379:6379'
    networks:
      - walking_rabbit_api_network
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
networks:
  walking_rabbit_api_network:
volumes:
  db-volume:
